import { ScanResult, Bug, BugSeverity } from '../types.js';

export function outputMarkdown(result: ScanResult): string {
  const lines: string[] = [];
  const verifiedBugs = result.bugs.filter((b) => b.kind === 'bug');
  const smells = result.bugs.filter((b) => b.kind === 'smell');

  // Header
  lines.push('# Bug Report');
  lines.push('');
  lines.push(`> Generated by [whiterose](https://github.com/shakecodeslikecray/whiterose) on ${new Date().toISOString()}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| | Bugs | Smells |`);
  lines.push(`|----------|-------|-------|`);
  lines.push(`| Critical | ${result.summary.bugs.critical} | ${result.summary.smells.critical} |`);
  lines.push(`| High | ${result.summary.bugs.high} | ${result.summary.smells.high} |`);
  lines.push(`| Medium | ${result.summary.bugs.medium} | ${result.summary.smells.medium} |`);
  lines.push(`| Low | ${result.summary.bugs.low} | ${result.summary.smells.low} |`);
  lines.push(`| **Total** | **${result.summary.bugs.total}** | **${result.summary.smells.total}** |`);
  lines.push('');
  lines.push(`**Total Findings:** ${result.summary.total}`);
  lines.push('');

  // Scan info
  lines.push(`- **Scan Type:** ${result.scanType}`);
  lines.push(`- **Files Scanned:** ${result.filesScanned}`);
  if (result.filesChanged !== undefined) {
    lines.push(`- **Files Changed:** ${result.filesChanged}`);
  }
  lines.push('');

  if (verifiedBugs.length === 0 && smells.length === 0) {
    lines.push('No findings found.');
    return lines.join('\n');
  }

  if (verifiedBugs.length === 0 && smells.length > 0) {
    lines.push('No verified bugs found. Smells are listed below.');
    lines.push('');
  }

  // Group by severity
  const bySeverity: Record<BugSeverity, Bug[]> = {
    critical: [],
    high: [],
    medium: [],
    low: [],
  };

  for (const bug of verifiedBugs) {
    bySeverity[bug.severity].push(bug);
  }

  if (verifiedBugs.length > 0) {
    lines.push('## Verified Bugs');
    lines.push('');
    emitBySeverity(lines, bySeverity);
  }

  if (smells.length > 0) {
    const smellsBySeverity: Record<BugSeverity, Bug[]> = {
      critical: [],
      high: [],
      medium: [],
      low: [],
    };

    for (const smell of smells) {
      smellsBySeverity[smell.severity].push(smell);
    }

    lines.push('## Smells');
    lines.push('');
    emitBySeverity(lines, smellsBySeverity);
  }

  return lines.join('\n');
}

function emitBySeverity(lines: string[], bySeverity: Record<BugSeverity, Bug[]>): void {
  if (bySeverity.critical.length > 0) {
    lines.push('### Critical');
    lines.push('');
    for (const bug of bySeverity.critical) {
      lines.push(formatBug(bug));
    }
  }

  if (bySeverity.high.length > 0) {
    lines.push('### High');
    lines.push('');
    for (const bug of bySeverity.high) {
      lines.push(formatBug(bug));
    }
  }

  if (bySeverity.medium.length > 0) {
    lines.push('### Medium');
    lines.push('');
    for (const bug of bySeverity.medium) {
      lines.push(formatBug(bug));
    }
  }

  if (bySeverity.low.length > 0) {
    lines.push('### Low');
    lines.push('');
    for (const bug of bySeverity.low) {
      lines.push(formatBug(bug));
    }
  }
}

function formatBug(bug: Bug): string {
  const lines: string[] = [];

  // Title with ID and confidence
  const confidenceBadge = getConfidenceBadge(bug.confidence.overall);
  const kindBadge = bug.kind === 'smell' ? '`[SMELL]`' : '`[BUG]`';
  lines.push(`### ${bug.id}: ${bug.title} ${kindBadge} ${confidenceBadge}`);
  lines.push('');

  // Location
  lines.push(`**Location:** \`${bug.file}:${bug.line}\``);
  lines.push(`**Category:** ${formatCategory(bug.category)}`);
  lines.push('');

  // Description
  lines.push(bug.description);
  lines.push('');

  // Code path
  if (bug.codePath.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Code Path</summary>');
    lines.push('');
    for (const step of bug.codePath) {
      lines.push(`${step.step}. \`${step.file}:${step.line}\``);
      lines.push(`   \`\`\`${getLanguage(step.file)}`);
      lines.push(`   ${step.code}`);
      lines.push('   ```');
      lines.push(`   ${step.explanation}`);
      lines.push('');
    }
    lines.push('</details>');
    lines.push('');
  }

  // Evidence
  if (bug.evidence.length > 0) {
    lines.push('**Evidence:**');
    for (const e of bug.evidence) {
      lines.push(`- ${e}`);
    }
    lines.push('');
  }

  // Suggested fix
  if (bug.suggestedFix) {
    lines.push('**Suggested Fix:**');
    lines.push('```');
    lines.push(bug.suggestedFix);
    lines.push('```');
    lines.push('');
  }

  lines.push('---');
  lines.push('');

  return lines.join('\n');
}

function getConfidenceBadge(confidence: string): string {
  switch (confidence) {
    case 'high':
      return '`[HIGH CONFIDENCE]`';
    case 'medium':
      return '`[MEDIUM CONFIDENCE]`';
    case 'low':
      return '`[LOW CONFIDENCE]`';
    default:
      return '';
  }
}

function formatCategory(category: string): string {
  return category
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function getLanguage(file: string): string {
  if (file.endsWith('.ts') || file.endsWith('.tsx')) return 'typescript';
  if (file.endsWith('.js') || file.endsWith('.jsx')) return 'javascript';
  if (file.endsWith('.py')) return 'python';
  if (file.endsWith('.go')) return 'go';
  return '';
}
